# Generated by Django 5.0.6 on 2024-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=120, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=120, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=120, verbose_name='отчество')),
                ('data_of_birth', models.DateField(verbose_name='дата рождения')),
                ('SNILS', models.CharField(blank=True, max_length=14, null=True, verbose_name='СНИЛС')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='электронная почта')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='individuals/', verbose_name='аватар')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'Физическое лицо',
                'verbose_name_plural': 'Физические лица',
                'ordering': ['moderator'],
            },
        ),
    ]
