# Generated by Django 5.0.6 on 2024-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_public_of_moderators',
            field=models.BooleanField(default=False, verbose_name='публичный ли для модераторов'),
        ),
    ]
