# Generated by Django 5.0.6 on 2024-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='is_status',
            field=models.BooleanField(choices=[('A', 'администратор'), ('M', 'модератор'), ('S', 'обучающийся')], max_length=1, verbose_name='статус группы'),
        ),
    ]
