# Generated by Django 5.0.6 on 2024-06-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOUTCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sout_card_number', models.CharField(max_length=120, verbose_name='номер карты СОУТ')),
                ('date_of_card_creation', models.DateTimeField(verbose_name='дата создания карты СОУТ')),
                ('ut_class', models.CharField(choices=[(10, 'optimal'), (20, 'permissible'), (31, 'harmful labor conditions of the 1'), (32, 'harmful labor conditions of the 2'), (33, 'harmful labor conditions of the 3'), (34, 'harmful labor conditions of the 4'), (40, 'hazardous labor conditions')], max_length=2, verbose_name='класс УТ')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='администратор')),
            ],
            options={
                'verbose_name': 'Карта СОУТ',
                'verbose_name_plural': 'Карты СОУТ',
            },
        ),
    ]
