# Generated by Django 5.0.6 on 2024-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutcard',
            name='ut_class',
            field=models.CharField(choices=[(10, 'оптимальные'), (20, 'допустимые'), (31, 'вредные условия труда 1 степени'), (32, 'вредные условия труда 2 степени'), (33, 'вредные условия труда 3 степени'), (34, 'вредные условия труда 4 степени'), (40, 'опасные условия труда')], max_length=2, verbose_name='класс УТ'),
        ),
    ]
