# Generated by Django 5.0.6 on 2024-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0002_alter_soutcard_ut_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutcard',
            name='date_of_card_creation',
            field=models.DateField(verbose_name='дата создания карты СОУТ'),
        ),
    ]
