# Generated by Django 5.0.6 on 2024-06-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplaces', '0003_alter_soutcard_date_of_card_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soutcard',
            options={'ordering': ['sout_card_number'], 'verbose_name': 'Карта СОУТ', 'verbose_name_plural': 'Карты СОУТ'},
        ),
    ]
