# Generated by Django 5.0.6 on 2024-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='вопрос')),
                ('question_text', models.CharField(max_length=400, verbose_name='текст вопроса')),
                ('option_a', models.CharField(max_length=250, verbose_name='вариант A')),
                ('option_b', models.CharField(max_length=250, verbose_name='вариант B')),
                ('option_c', models.CharField(blank=True, max_length=250, null=True, verbose_name='вариант C')),
                ('option_d', models.CharField(blank=True, max_length=250, null=True, verbose_name='вариант D')),
                ('correct_option', models.CharField(choices=[('A', 'option_a'), ('B', 'option_b'), ('C', 'option_c'), ('D', 'option_d')], max_length=1, verbose_name='правильный вариант')),
                ('topic', models.CharField(max_length=120, verbose_name='тема')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='пояснение')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='название теста')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('self_assessment', models.BooleanField(default=False, verbose_name='самопроверка')),
                ('execution_time', models.PositiveIntegerField(verbose_name='время на выполнение')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'тест',
                'verbose_name_plural': 'тесты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_to_questions', models.JSONField(verbose_name='ответы на вопросы')),
                ('score', models.PositiveIntegerField(verbose_name='количество правильных ответов')),
                ('result', models.CharField(choices=[(0, 'failed'), (1, 'passed')], max_length=1, verbose_name='результат')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'тестирование',
                'verbose_name_plural': 'тестирования',
                'ordering': ['result'],
            },
        ),
    ]
