# Generated by Django 5.0.6 on 2024-06-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_testing', '0002_initial'),
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='additionmaterial',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AddField(
            model_name='module',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AddField(
            model_name='module',
            name='self_assessment_test',
            field=models.ManyToManyField(blank=True, related_name='modules', to='knowledge_testing.test', verbose_name='тесты'),
        ),
        migrations.AddField(
            model_name='program',
            name='list_modules',
            field=models.ManyToManyField(blank=True, to='materials.module', verbose_name='модули'),
        ),
        migrations.AddField(
            model_name='program',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AddField(
            model_name='program',
            name='self_assessment_test',
            field=models.ManyToManyField(blank=True, related_name='programs', to='knowledge_testing.test', verbose_name='тесты'),
        ),
        migrations.AddField(
            model_name='topic',
            name='additional_materials',
            field=models.ManyToManyField(blank=True, to='materials.additionmaterial', verbose_name='доп. материалы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='модератор'),
        ),
        migrations.AddField(
            model_name='module',
            name='list_topics',
            field=models.ManyToManyField(blank=True, to='materials.topic', verbose_name='темы'),
        ),
    ]
