# Generated by Django 5.0.6 on 2024-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='additional_materials',
            new_name='addition_materials',
        ),
    ]
