# Generated by Django 5.0.6 on 2024-06-01 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        ('materials', '0002_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmatrix',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='администратор'),
        ),
        migrations.AddField(
            model_name='trainingmatrix',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.position', verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='trainingmatrix',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.program', verbose_name='программа'),
        ),
    ]
