# Generated by Django 5.0.6 on 2024-06-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'структурное подразделение',
                'verbose_name_plural': 'структурные подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=220, verbose_name='полное название')),
                ('short_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='сокращенное название')),
                ('tin', models.CharField(blank=True, max_length=9, null=True, verbose_name='ИНН')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество сотрудников')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.CharField(blank=True, max_length=120, null=True, verbose_name='табельный номер')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='дата приема на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='дата увольнения c работы')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_update', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'работники',
                'ordering': ['moderator'],
            },
        ),
    ]
